title: Ana. Is a very short name. 
permalink: /blog/:year/:month/:day/:title
github_username:  electro-swing
theme: jekyll-theme-minimal
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
  


